apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-inspector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-inspector
  template:
    metadata:
      labels:
        app: mcp-inspector
    spec:
      containers:
      - name: mcp-inspector
        image: registry.access.redhat.com/ubi9/nodejs-22@sha256:ae0a4313f9e709e370998b76f51e57622799c5a3155446276db5953dbcaedc05
        command: ["/bin/bash", "-c"]
        args:
          - "npx @modelcontextprotocol/inspector"
        ports:
          - containerPort: 5173
            name: http
          - containerPort: 3000
            name: proxy-server

---
apiVersion: v1
kind: Service
metadata:
  name: mcp-inspector
spec:
  type: ClusterIP
  selector:
    app: mcp-inspector
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5173

---
apiVersion: v1
kind: Service
metadata:
  name: proxy-server
spec:
  type: ClusterIP
  selector:
    app: mcp-inspector
  ports:
    - name: proxy-server
      protocol: TCP
      port: 80
      targetPort: 3000

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mcp-inspector
spec:
  to:
    kind: Service
    name: mcp-inspector
  port:
    targetPort: http