apiVersion: v1
kind: Secret
metadata:
  name: grafana-sa-token
  namespace: observability-hub
  annotations:
    kubernetes.io/service-account.name: grafana-sa
type: kubernetes.io/service-account-token
