apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: vllm
  name: vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vllm
    spec:
      containers:
      - args:
        - --tensor-parallel-size=2
        - --model
        - ibm-granite/granite-3.2-8b-instruct
        - --enable-auto-tool-choice
        - --chat-template
        - /app/tool_chat_template_granite.jinja
        - --tool-call-parser=granite
        - --port
        - "8000"
        env:
        - name: VLLM_PORT
          value: "8000"
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: HF_TOKEN
              name: huggingface-secret
        image: vllm/vllm-openai:v0.7.3
        imagePullPolicy: Always
        name: vllm
        ports:
        - containerPort: 8000
          protocol: TCP
        resources:
          limits:
            nvidia.com/gpu: "2"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /.cache
          name: hf-cache
        - mountPath: /.triton
          name: triton
        - mountPath: /app
          name: chat-template
        - mountPath: /.config
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: hf-cache
      - emptyDir: {}
        name: triton
      - configMap:
          defaultMode: 420
          name: granite-chat 
        name: chat-template
      - emptyDir: {}
        name: config
